### ISSUE TITLE
新增文章页面跳转不了

### ISSUE THREAD

**Issue by holyong123** [martin-chips/DimpleBlog#30]
我pull了master的源码，但是后台新增文章的时候，页面跳转404.html,请问后台的博文新增页面跳转应该怎么修改

**Comment by ox123** [comment]
refer to this issues:  https://github.com/DimpleFeng/DimpleBlog/issues/26

**Comment by AsukaThunder** [comment]
<router-link :to="{ path: '/blogManage/blog/add' }" class="link-type">
          <el-button type="primary" icon="el-icon-plus" size="mini">新增
          </el-button>
        </router-link>

**Comment by SunYang666216** [comment]
你们好呀，有大佬愿意为我搭一下这个项目马
